[package]
name = "alder-solve"
version = "0.3.0"
edition.workspace = true
description = "The entry point of alder's type inference system. Implements type inference and specialization of traits."
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
bumpalo.workspace = true
alder-ast = { path = "../alder-ast", version = "0.2.0" }
alder-can = { path = "../alder-can", version = "0.3.0" }
alder-constrain = { path = "../alder-constrain", version = "0.3.0" }
alder-region = { path = "../alder-region", version = "0.2.0" }

[dev-dependencies]
indoc.workspace = true
insta.workspace = true
alder-parse = { path = "../alder-parse" }
alder-source = { path = "../alder-source" }
