[package]
name = "alder-report"
version = "0.2.0"
edition.workspace = true
description = "Structured source diagnostics for the Alder compiler"
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
miette.workspace = true
thiserror.workspace = true

alder-region = { path = "../alder-region", version = "0.2.0" }

[dev-dependencies]
indoc.workspace = true
insta.workspace = true
