[package]
name = "alder-parse"
version = "0.2.0"
edition.workspace = true
description = "Parser for the alder programming language"
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
bumpalo.workspace = true
alder-region = { path = "../alder-region", version = "0.2.0" }
alder-source = { path = "../alder-source", version = "0.2.0" }

[dev-dependencies]
indoc.workspace = true
insta.workspace = true
