#!/usr/bin/env python3
"""Generate WHATWG tables offline from a pinned source (--refresh updates it).

The Living Standard index uses omitted table end tags. Split its explicit row
and cell starts, extracting code terms, rather than relying on XML parsing.
"""
import argparse
import hashlib
import gzip
import html
import pathlib
import re
import subprocess
import urllib.request

URL = "https://html.spec.whatwg.org/multipage/indices.html"
ROOT = pathlib.Path(__file__).resolve().parents[1]
SOURCE = ROOT / "tools/html-schema-source.html.gz"
TARGET = ROOT / "crates/alder-solve/src/html_schema/generated.rs"


def text(value):
    return " ".join(html.unescape(re.sub(r"<[^>]*>", "", value)).split())


def codes(value):
    return [text(part) for part in re.findall(r"<code\b[^>]*>(.*?)</code>", value, re.S)]


def rows(table):
    return [re.split(r"<t[dh]\b[^>]*>", row)[1:] for row in re.split(r"<tr\b[^>]*>", table)[1:]]


parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--source", type=pathlib.Path, default=SOURCE, help="pinned offline HTML input")
parser.add_argument("--output", type=pathlib.Path, default=TARGET)
parser.add_argument("--refresh", action="store_true", help="fetch WHATWG and replace the source snapshot")
parser.add_argument("--check", action="store_true", help="verify generated output without writes or network")
args = parser.parse_args()
if args.refresh and args.check:
    parser.error("--refresh and --check are mutually exclusive")
if args.refresh:
    raw = urllib.request.urlopen(URL, timeout=60).read()
    args.source.write_bytes(gzip.compress(raw, mtime=0) if args.source.suffix == ".gz" else raw)
source_bytes = args.source.read_bytes()
if args.source.suffix == ".gz":
    source_bytes = gzip.decompress(source_bytes)
source = source_bytes.decode()
tables = re.findall(r"<table\b[^>]*>(.*?)</table>", source, re.S)
elements = next(table for table in tables if "<caption>List of elements</caption>" in table)
attributes = next(table for table in tables if "<caption>List of attributes" in table)
attribute_types = {}
globals_ = set()
for cells in rows(attributes):
    if len(cells) < 4 or not codes(cells[0]):
        continue
    name = codes(cells[0])[0]
    value = text(cells[3]).lower()
    kind = "Bool" if "boolean attribute" in value else "Number" if value.startswith(("valid integer", "valid non-negative integer", "valid floating-point number")) and ";" not in value else "String"
    for tag in codes(cells[1]):
        attribute_types[(tag, name)] = kind
    if "HTML elements" in text(cells[1]):
        globals_.add(name)
        attribute_types[("*", name)] = kind

output = ["// Generated by tools/generate-html-schema.py from " + URL,
          "// Source HTML SHA-256: " + hashlib.sha256(source_bytes).hexdigest(),
          "// Checked in so ordinary compiler builds never fetch the schema.",
          "use super::{AttributeType, Element};", "pub(super) const ELEMENTS: &[Element] = &["]
count = 0
for cells in rows(elements):
    if len(cells) != 7 or not codes(cells[0]):
        continue
    for name in codes(cells[0]):
        attrs = sorted(set(codes(cells[5])))
        attrs = [a for a in attrs if not a.startswith("on")]
        overrides = {("li", "value"): "Number", ("meter", "value"): "Number", ("progress", "value"): "Number", ("meter", "min"): "Number", ("meter", "max"): "Number", ("progress", "max"): "Number"}
        values = ", ".join('(\"' + a + '\", AttributeType::' + overrides.get((name, a), attribute_types.get((name, a), "String")) + ')' for a in attrs)
        output.append('    Element { name: "' + name + '", phrasing: ' + str("phrasing" in text(cells[2])).lower() + ', phrasing_children: ' + str(text(cells[4]).rstrip("*") == "phrasing").lower() + ', void: ' + str(text(cells[4]) == "empty").lower() + ', attrs: &[' + values + '] },')
        count += 1
assert count > 100, count
output.extend(["];", "pub(super) const GLOBALS: &[(&str, AttributeType)] = &["])
for name in sorted(globals_):
    if not name.startswith("on"):
        output.append('    ("' + name + '", AttributeType::' + attribute_types[("*", name)] + '),')
output.append("];")
formatted = subprocess.run(["rustfmt", "--edition", "2024", "--emit", "stdout"], input="\n".join(output) + "\n", text=True, capture_output=True, check=True).stdout
if args.check:
    if args.output.read_text() != formatted:
        raise SystemExit("HTML schema is stale; run python3 tools/generate-html-schema.py")
    print("HTML schema matches its pinned source snapshot")
else:
    args.output.parent.mkdir(exist_ok=True)
    args.output.write_text(formatted)
    print(f"Generated {count} elements and {len(globals_)} global attributes: {args.output}")
