[package]
name = "alder-config"
version = "0.2.1"
edition.workspace = true
description = "Alder project configuration file parsing"
readme = "README.md"
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
jsonc-parser.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
indoc.workspace = true
