[package]
name = "alder-codegen"
version = "0.4.0"
edition.workspace = true
description = "JavaScript code generation for Alder"
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
alder-ast = { path = "../alder-ast", version = "0.3.0" }
alder-region = { path = "../alder-region", version = "0.2.0" }
alder-solve = { path = "../alder-solve", version = "0.4.0" }
rolldown_ecmascript = "=0.1.0"
oxc_allocator = "=0.95.0"
oxc_ast = "=0.95.0"
oxc_codegen = "=0.95.0"
oxc_span = "=0.95.0"
oxc_syntax = "=0.95.0"

[dev-dependencies]
alder-can = { path = "../alder-can" }
alder-constrain = { path = "../alder-constrain" }
alder-parse = { path = "../alder-parse" }
bumpalo.workspace = true
indoc.workspace = true
insta.workspace = true
