[package]
name = "alder-ast"
version = "0.1.0"
edition.workspace = true
description = "Canonical AST for the alder programming language"
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
alder-region = { path = "../alder-region", version = "0.1.0" }
alder-source = { path = "../alder-source", version = "0.1.0" }
